# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-12 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0057_remove_processrun_rto'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostsmanage',
            name='host_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='主机类型'),
        ),
        migrations.AddField(
            model_name='hostsmanage',
            name='oracle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='oracle用户名'),
        ),
        migrations.AddField(
            model_name='hostsmanage',
            name='oracle_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='oracle密码'),
        ),
    ]
