# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-13 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0060_auto_20191113_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='hosts_manage',
        ),
        migrations.AlterField(
            model_name='process',
            name='main_database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_database', to='faconstor.HostsManage', verbose_name='主机管理'),
        ),
        migrations.AlterField(
            model_name='process',
            name='prepare_database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepare_database', to='faconstor.HostsManage', verbose_name='主机管理'),
        ),
    ]
