# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-13 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0062_auto_20191113_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='hosts_manage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.HostsManage', verbose_name='主机管理'),
        ),
        migrations.AddField(
            model_name='process',
            name='main_database',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主数据库'),
        ),
        migrations.AddField(
            model_name='process',
            name='prepare_database',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备数据库'),
        ),
    ]
