# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-13 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0064_remove_process_hosts_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='hosts_manage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.HostsManage', verbose_name='主机管理'),
        ),
    ]
