# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-14 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0065_process_hosts_manage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='hosts_manage',
        ),
        migrations.RemoveField(
            model_name='process',
            name='main_database',
        ),
        migrations.RemoveField(
            model_name='process',
            name='prepare_database',
        ),
        migrations.AddField(
            model_name='process',
            name='primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_primary_set', to='faconstor.HostsManage', verbose_name='主数据库'),
        ),
        migrations.AddField(
            model_name='process',
            name='standby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_standby_set', to='faconstor.HostsManage', verbose_name='备数据库'),
        ),
    ]
