# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-14 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0067_auto_20191114_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsmanage',
            name='host_type',
            field=models.IntegerField(choices=[(1, '主数据库'), (2, '备数据库'), (3, '其他')], null=True, verbose_name='主机类型'),
        ),
    ]
