# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-14 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0068_auto_20191114_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostsmanage',
            name='oracle_instance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='oracle实例名称'),
        ),
    ]
