# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-25 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0069_hostsmanage_oracle_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='backprocess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_backprocess_set', to='faconstor.Process', verbose_name='回切流程'),
        ),
    ]
